-- MySQL Script generated by MySQL Workbench
-- Tue Sep 17 23:45:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Escola_Informatica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Escola_Informatica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Escola_Informatica` DEFAULT CHARACTER SET utf8 ;
USE `Escola_Informatica` ;

-- -----------------------------------------------------
-- Table `Escola_Informatica`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola_Informatica`.`aluno` (
  `idaluno` INT NOT NULL AUTO_INCREMENT,
  `nome_aluno` VARCHAR(45) NOT NULL,
  `endereco_aluno` VARCHAR(45) NOT NULL,
  `telefone_aluno` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `altura` DOUBLE NOT NULL,
  `peso` DOUBLE NOT NULL,
  PRIMARY KEY (`idaluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Informatica`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola_Informatica`.`professor` (
  `idCPF_professor` INT NOT NULL AUTO_INCREMENT,
  `nome_professor` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `titulacao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCPF_professor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Informatica`.`aluno_monitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola_Informatica`.`aluno_monitor` (
  `idaluno_monitor` INT NOT NULL AUTO_INCREMENT,
  `nome_monitor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idaluno_monitor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Informatica`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola_Informatica`.`turma` (
  `idturma` INT NOT NULL AUTO_INCREMENT,
  `qtd_alunos` INT NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `duracao` VARCHAR(45) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_final` DATE NOT NULL,
  `tipo_curso` VARCHAR(45) NOT NULL,
  `professor_CPF_professor` INT NOT NULL,
  `aluno_monitor_idaluno_monitor` INT NOT NULL,
  PRIMARY KEY (`idturma`),
  INDEX `fk_turma_professor1_idx` (`professor_CPF_professor` ASC) VISIBLE,
  INDEX `fk_turma_aluno_monitor1_idx` (`aluno_monitor_idaluno_monitor` ASC) VISIBLE,
  CONSTRAINT `fk_turma_professor1`
    FOREIGN KEY (`professor_CPF_professor`)
    REFERENCES `Escola_Informatica`.`professor` (`idCPF_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_aluno_monitor1`
    FOREIGN KEY (`aluno_monitor_idaluno_monitor`)
    REFERENCES `Escola_Informatica`.`aluno_monitor` (`idaluno_monitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Informatica`.`contatos_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola_Informatica`.`contatos_professor` (
  `idcontatos_professor` INT NOT NULL AUTO_INCREMENT,
  `telefone_professor` VARCHAR(45) NOT NULL,
  `professor_CPF_professor` INT NOT NULL,
  PRIMARY KEY (`idcontatos_professor`),
  INDEX `fk_telefones_professor_professor_idx` (`professor_CPF_professor` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_professor_professor`
    FOREIGN KEY (`professor_CPF_professor`)
    REFERENCES `Escola_Informatica`.`professor` (`idCPF_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Informatica`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola_Informatica`.`matricula` (
  `idmatricula` INT NOT NULL AUTO_INCREMENT,
  `ausencias` INT NOT NULL,
  `data_matricula` DATE NOT NULL,
  `aluno_idaluno` INT NOT NULL,
  `turma_idturma` INT NOT NULL,
  PRIMARY KEY (`idmatricula`),
  INDEX `fk_matricula_aluno1_idx` (`aluno_idaluno` ASC) VISIBLE,
  INDEX `fk_matricula_turma1_idx` (`turma_idturma` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `Escola_Informatica`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_turma1`
    FOREIGN KEY (`turma_idturma`)
    REFERENCES `Escola_Informatica`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
